apiVersion: v1
kind: Service
metadata:
  name: {{ include "movies-service.fullname" . }}
  labels:
  {{- include "movies-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.appService.type }}

  selector:
    app: movies-service
  {{- include "movies-service.selectorLabels" . | nindent 4 }}

  ports:
  {{- .Values.appService.ports | toYaml | nindent 2 -}}