apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
  {{- include "movies-service.labels" . | nindent 4 }}
data:
  app.security.tmdb.key: {{ required "secrets.appSecurityTmdbKey is required" .Values.secrets.appSecurityTmdbKey | b64enc | quote }}
type: Opaque