apiVersion: v1
kind: ConfigMap
metadata:
  name: movies-config
data:
  environment: local-movies
  management.endpoints.web.exposure.include: "*"
---
apiVersion: v1
kind: Secret
metadata:
  name: movies-secrets
type: Opaque
data:
  app.security.tmdb.key: ZTQ3NTcwMzY0Y2M4Y2U0MGRmZmI1Yjc4NTA5N2RlY2Y=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-service-deployment
  labels:
    app: movies-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movies-service
  template:
    metadata:
      annotations:
        prometheus.io/path: /api/actuator/prometheus
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
      labels:
        app: movies-service
        version: v1
    spec:
      containers:
      - name: movies-service
        image: localhost:5001/movies-service:latest
        ports:
        - containerPort: 8080
        env:
          - name: environment
            value: general-movies
          - name: TMDB_API_KEY
            valueFrom:
              secretKeyRef:
                name: movies-secrets
                key: app.security.tmdb.key
          - name: management.endpoints.web.exposure.include
            valueFrom:
              configMapKeyRef:
                name: movies-config
                key: management.endpoints.web.exposure.include
        livenessProbe:
          httpGet:
            path: "/api/actuator/health/liveness"
            port: 8080
            scheme: HTTP
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: "/api/actuator/health/readiness"
            port: 8080
            scheme: HTTP
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: movies-service-srv
spec:
  type: ClusterIP
  selector:
    app: movies-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP