apiVersion: v1
kind: ConfigMap
metadata:
  name: moviesservice
data:
  environment: local-movies
  management.endpoints.web.exposure.include: "*"
  services.app.port: "80"
---
apiVersion: v1
kind: Secret
metadata:
  name: moviesservice
type: Opaque
data:
  app.security.tmdb.key: ZTQ3NTcwMzY0Y2M4Y2U0MGRmZmI1Yjc4NTA5N2RlY2Y=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviesservice
  labels:
    app: moviesservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moviesservice
  template:
    metadata:
      annotations:
        prometheus.io/path: /api/actuator/prometheus
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
      labels:
        app: moviesservice
        version: v1
    spec:
      containers:
        - name: moviesservice
          image: eder/moviesservice:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: environment
              value: general-movies
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: moviesservice
                  key: services.app.port
            - name: TMDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: moviesservice
                  key: app.security.tmdb.key
            - name: management.endpoints.web.exposure.include
              valueFrom:
                configMapKeyRef:
                  name: moviesservice
                  key: management.endpoints.web.exposure.include
          livenessProbe:
            httpGet:
              path: "/api/actuator/health/liveness"
              port: 80
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: "/api/actuator/health/readiness"
              port: 80
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: moviesservice
spec:
  type: ClusterIP
  selector:
    app: moviesservice
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP