apiVersion: v1
kind: ConfigMap
metadata:
  name: moviesbff
data:
  environment: local-movies
  services.app.port: "80"
  services.url.movies: "http://moviesservice"
  services.port.movies: "80"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviesbff
  labels:
    app: moviesbff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moviesbff
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
      labels:
        app: moviesbff
        version: v1
    spec:
      containers:
        - name: movies-bff
          image: eder/moviesbff:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: environment
              value: general-movies
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: moviesbff
                  key: services.app.port
            - name: SERVICES_URL_MOVIES
              valueFrom:
                configMapKeyRef:
                  name: moviesbff
                  key: services.url.movies
            - name: SERVICES_PORT_MOVIES
              valueFrom:
                configMapKeyRef:
                  name: moviesbff
                  key: services.port.movies
          livenessProbe:
            httpGet:
              path: "/actuator/health/liveness"
              port: 80
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: "/actuator/health/readiness"
              port: 80
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: moviesbff
spec:
  type: ClusterIP
  selector:
    app: moviesbff
  ports:
    - name: http
      port: 80
      protocol: TCP

