version: '3'
services:
  moviesservice:
    env_file:
      - local-development-moviesservice.env
    build:
      dockerfile: Dockerfile
      context: ../../movies-service
    ports:
      - '8085:8080'
  moviesbff:
    env_file:
      - local-development-moviesbff.env
    restart: always
    build:
      dockerfile: Dockerfile
      context: ../../movies-bff
    ports:
      - '8080:8080'
  moviesfrontend:
    env_file:
      - local-development-moviesfrontend.env
    restart: always
    build:
      dockerfile: Dockerfile
      context: ../../movies-frontend
    ports:
      - '8050:8050'